onlyBuiltDependencies:
  - electron
overrides:
  "brace-expansion@>=2.0.0 <3": 2.1.2
  body-parser: 2.3.0
  path-to-regexp: 8.4.0
  picomatch: 4.0.4
  qs: 6.15.2
  vite: npm:rolldown-vite@^7.3.1
patchedDependencies:
  vite-plugin-monaco-editor@1.1.0: patches/vite-plugin-monaco-editor@1.1.0.patch
